### ISSUE TITLE
Custom type using Attributor::Type not serialized properly

### ISSUE THREAD

**Issue by Ventajou** [rightscale/praxis-blueprints#26]
I have a custom type called `RecurrenceRule`, it represents a native type of `IceCube::Rule` and does some special serialization from a specific string format to the native type and back.

In the past (before Praxis 0.19), media types using the `RecurrenceRule` would be rendered properly. But now, the `dump` method on `RecurrenceRule` is no longer called when rendering the media type. Resulting in the native type being returned as a JSON object.

**Comment by aliscott** [comment]
It would be nice if we also allow this to work with custom types that implement `member_attribute`. In this case the `fields` argument to `Renderer#render` will be `[true]`.

As an example we have a custom set type (https://gist.github.com/aliscott/afa5db20f885423cc5c9) that needs this.
